GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###
///1
GET http://localhost:3000/todos/?status=TO%20DO

###
//2
GET http://localhost:3000/todos/?priority=LOW

###
///3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###
///4
GET http://localhost:3000/todos/?search_q=buy

###
///5
GET http://localhost:3000/todos/?category=LEARNING&status=IN%20PROGRESS

###
///6
GET http://localhost:3000/todos/?category=HOME

###
///7
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###
GET  http://localhost:3000/agenda/?date=2021-12-12